#ifndef _CID_GENETIC_H_
#define _CID_GENETIC_H_

/**
 * @file Genetic.h
 * @author James Edmondson <james.r.edmondson@vanderbilt.edu>
 *
 * This file contains declarations of genetic algorithms that may be useful in
 * improving a deployment generated by the CID heuristic.
 */

#include "Settings.h"
#include "madara/MADARA_export.h"

namespace Madara
{
  namespace Cid
  {
    MADARA_Export void ga_naive (Settings & settings,
      unsigned int max_mutations);

    MADARA_Export void ga_degree (Settings & settings,
      unsigned int max_mutations);

  } // end namespace Cid

} // end namespace Madara

#endif 