#ifndef _CID_GENETIC_H_
#define _CID_GENETIC_H_

/**
 * @file Genetic.h
 * @author James Edmondson <james.r.edmondson@vanderbilt.edu>
 *
 * This file contains declarations of genetic algorithms that may be useful in
 * improving a deployment generated by the CID heuristic.
 */

#endif 