
module Knowledge
{
    struct Update
    {
      string                            key;
      long long                         value;
      unsigned long                     quality;
      string                            originator;
      unsigned long                     type;
      unsigned long long                clock;
    };
    
    //#pragma keylist Update
    #pragma keylist    Update     originator     
};