//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Splice_Knowledge_Update.cpp
//  Source: include/madara/transport/splice/Splice_Knowledge_Update.idl
//  Generated: Wed Jan 11 23:55:01 2012
//  OpenSplice V5.2.0
//  
//******************************************************************

#include "Splice_Knowledge_Update.h"




