//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Splice_Knowledge_Update.h
//  Source: include/madara/transport/splice/Splice_Knowledge_Update.idl
//  Generated: Wed Jan 11 23:55:01 2012
//  OpenSplice V5.2.0
//  
//******************************************************************
#ifndef _SPLICE_KNOWLEDGE_UPDATE_H_
#define _SPLICE_KNOWLEDGE_UPDATE_H_


#include "sacpp_mapping.h"
#include "sacpp_DDS_DCPS.h"

namespace Knowledge
{
   struct Update;

   struct Update
   {
      DDS::String_mgr key;
      DDS::LongLong value;
      DDS::ULong quality;
      DDS::String_mgr originator;
      DDS::ULong type;
      DDS::ULongLong clock;
   };

   typedef DDS_DCPSStruct_var < Update> Update_var;
   typedef DDS_DCPSStruct_out < Update> Update_out;
}




#endif 
