/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_String */

#ifndef _Included_com_madara_containers_String
#define _Included_com_madara_containers_String
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_String
 * Method:    jni_String
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_String_jni_1String__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_String
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_String_jni_1String__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_freeString
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_String_jni_1freeString
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_set
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_String_jni_1set
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_String_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_String_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_String_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_toDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_madara_containers_String_jni_1toDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_String
 * Method:    jni_toLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_String_jni_1toLong
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
