/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_Vector */

#ifndef _Included_com_madara_containers_Vector
#define _Included_com_madara_containers_Vector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_Vector
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Vector_jni_1Vector__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_Vector
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Vector_jni_1Vector__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_freeVector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1freeVector
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_set
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1set__JILjava_lang_String_2
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_set
 * Signature: (JID)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1set__JID
  (JNIEnv *, jobject, jlong, jint, jdouble);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_set
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1set__JIJJ
  (JNIEnv *, jobject, jlong, jint, jlong, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_Vector_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_get
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Vector_jni_1get
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_toRecord
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Vector_jni_1toRecord
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_toArray
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_madara_containers_Vector_jni_1toArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Vector_jni_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Vector
 * Method:    jni_resize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Vector_jni_1resize
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
