/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_Integer */

#ifndef _Included_com_madara_containers_Integer
#define _Included_com_madara_containers_Integer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_Integer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Integer_jni_1Integer__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_Integer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Integer_jni_1Integer__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_freeInteger
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Integer_jni_1freeInteger
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_set
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Integer_jni_1set
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_Integer_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_setName
 * Signature: (JJLjava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Integer_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_toString
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_Integer_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_toDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_madara_containers_Integer_jni_1toDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Integer
 * Method:    jni_toLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Integer_jni_1toLong
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
