/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_StringVector */

#ifndef _Included_com_madara_containers_StringVector
#define _Included_com_madara_containers_StringVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_StringVector
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_StringVector_jni_1StringVector__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_StringVector
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_StringVector_jni_1StringVector__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_freeStringVector
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_StringVector_jni_1freeStringVector
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_set
 * Signature: (JILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_StringVector_jni_1set
  (JNIEnv *, jobject, jlong, jint, jstring);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_StringVector_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_StringVector_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_get
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_StringVector_jni_1get
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_toRecord
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_StringVector_jni_1toRecord
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_toArray
 * Signature: (J)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_madara_containers_StringVector_jni_1toArray
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_size
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_StringVector_jni_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_StringVector
 * Method:    jni_resize
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_StringVector_jni_1resize
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
