/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_Map */

#ifndef _Included_com_madara_containers_Map
#define _Included_com_madara_containers_Map
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Map
 * Method:    jni_Map
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Map_jni_1Map__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_Map
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Map_jni_1Map__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_freeMap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Map_jni_1freeMap
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_set
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Map_jni_1set__JLjava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_set
 * Signature: (JLjava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Map_jni_1set__JLjava_lang_String_2D
  (JNIEnv *, jobject, jlong, jstring, jdouble);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_set
 * Signature: (JLjava/lang/String;JJ)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Map_jni_1set__JLjava_lang_String_2JJ
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_madara_containers_Map_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_setName
 * Signature: (JJJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Map_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jstring);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_get
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Map_jni_1get
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_madara_containers_Map
 * Method:    jni_toRecord
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Map_jni_1toRecord
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
