/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_madara_containers_Double */

#ifndef _Included_com_madara_containers_Double
#define _Included_com_madara_containers_Double
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_madara_containers_Double
 * Method:    jni_Double
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Double_jni_1Double__
  (JNIEnv *, jobject);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_Double
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Double_jni_1Double__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_freeDouble
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Double_jni_1freeDouble
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_set
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Double_jni_1set
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_getName
 * Signature: (J)Lcom/madara/containers/String;
 */
JNIEXPORT jobject JNICALL Java_com_madara_containers_Double_jni_1getName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_setName
 * Signature: (JJJLcom/madara/containers/String;)V
 */
JNIEXPORT void JNICALL Java_com_madara_containers_Double_jni_1setName
  (JNIEnv *, jobject, jlong, jlong, jlong, jobject);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toString
 * Signature: (J)Lcom/madara/containers/String;
 */
JNIEXPORT jobject JNICALL Java_com_madara_containers_Double_jni_1toString
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toDouble
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_madara_containers_Double_jni_1toDouble
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_madara_containers_Double
 * Method:    jni_toLong
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_madara_containers_Double_jni_1toLong
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
