//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: Splice_Knowledge_Update.cpp
//  Source: Splice_Knowledge_Update.idl
//  Generated: Fri Aug 27 00:06:36 2010
//  OpenSplice V5.2.0
//  
//******************************************************************

#include "Splice_Knowledge_Update.h"




