
module Knowledge
{
    struct Update
    {
      string                            key;
      long                              value;
      long                              priority;
      string                            originator;
      long                              type;
      long                              clock;
    };
    
    //#pragma keylist Update
    #pragma keylist    Update     key     
};