
module Knowledge
{
    struct Update
    {
      string                            key;
      long                              value;
    };
    
    //#pragma keylist Update
    #pragma keylist    Update     key     
};